Resolução do exercicio #17
codingdojoangola/dojophp pull request #25
Opened 2017-10-20 21:10 UTC by acidiney

2017-10-20 21:50 UTC, acidiney commented
Eu não estou entendendo essa ***** do StyleCI qualé o problema *****

2017-10-20 23:12 UTC, JoseCage commented
> Eu não estou entendendo essa ***** do StyleCI qualé o problema *****

Dando uma olhada no resultado da analise vais entender o erro.. :-1: :-1: 

Mas fui ver e era algo não tão significante, era espaçamento (embora importa rsrs)..

2017-10-20 23:19 UTC, JoseCage requested changes

2017-10-20 23:19 UTC, JoseCage commented on app/ArrayDeInformacoes/controller.php
> +// Para invocar a classe GithubApi usando o "use" do autoload precisa
@acidiney Uma vez que esse exercício não se refere ao do Github #5 creio que essa informação confunde um pouco a pessoa que vê o ficheiro..

2017-10-20 23:19 UTC, JoseCage commented on app/ArrayDeInformacoes/controller.php
> +// Para invocar a classe GithubApi usando o "use" do autoload precisa
Sei que fizeste um **`duplicate file`** pra evitar trabalho, mas mude sempre as informações com base nos desafios..

2017-10-22 11:24 UTC, merged

2017-10-22 11:27 UTC, acidiney commented on app/ArrayDeInformacoes/controller.php
> +// Para invocar a classe GithubApi usando o "use" do autoload precisa
Fim e acabei esquecendo de revisar tudo, foi mal