Resolução do exercicio #16
codingdojoangola/dojophp pull request #26
Opened 2017-10-22 13:52 UTC by acidiney

O  mesmo contém a index, controller, ConvertJsonForArrayAPI e ConvertJsonForArrayTest

2017-10-22 18:23 UTC, JoseCage requested changes

2017-10-22 18:23 UTC, JoseCage commented on app/ConvertjsonToArray/controller.php
> + // Instaciando Classe ConvertJsonForArrayAPI passando o Caminho do arquivo codingdojo.json
Não vai funcionar online por conta do endereço **`localhost`**..

2017-10-22 18:45 UTC, acidiney commented on app/ConvertjsonToArray/controller.php
> + // Instaciando Classe ConvertJsonForArrayAPI passando o Caminho do arquivo codingdojo.json
Sim kkk, já pensei nisso por isso passei o caminho do https://github.com/codingdojoangola/dojophp/raw/desafios/data/codingdojo.json

2017-10-22 19:03 UTC, JoseCage commented on app/ConvertjsonToArray/controller.php
> + // Instaciando Classe ConvertJsonForArrayAPI passando o Caminho do arquivo codingdojo.json
> Sim kkk, já pensei nisso por isso passei o caminho do https://github.com/codingdojoangola/dojophp/raw/desafios/data/codingdojo.json

Aqui no meu navegador não aparece nada ao acessar..

2017-10-22 19:07 UTC, JoseCage requested changes

2017-10-22 19:07 UTC, JoseCage commented on app/ArrayDeInformacoes/controller.php
> +// Para invocar a classe GithubApi usando o "use" do autoload precisa
@acidiney continua fazendo menção a classe `GithubApi`.. 

Favor mudar sempre a documentação consoante o exercício.. Uma vez que o exercício referente a API do Github é outro..

2017-10-28 10:07 UTC, JoseCage approved these changes

2017-10-28 10:08 UTC, merged