E200
codingdojoangola/dojophp pull request #6
Opened 2017-09-09 20:08 UTC by e200

2017-09-09 20:32 UTC, JoseCage requested changes

2017-09-09 20:32 UTC, JoseCage commented on tests/ResolveIdadesTest.php
> +class ResolveIdadesTest extends TestCase
Seria interessante que comentasses também a classe de teste tal como na classe principal (a ser testada no caso)..

2017-09-09 20:32 UTC, JoseCage commented on tests/ResolveIdadesTest.php
> +class ResolveIdadesTest extends TestCase
Igualmente seria interessante ter uma página html em que seu método/função fosse testado conforme comentada no evento hoje.

2017-09-10 20:30 UTC, JoseCage commented
@e200 pode por favor melhorar o ponto que citei acima?

2017-09-11 08:52 UTC, e200 commented
. As Soon As Possible.

2017-09-11 11:21 UTC, JoseCage commented
> . As Soon As Possible.

Right..

2017-09-11 22:39 UTC, JoseCage approved these changes

2017-09-11 22:40 UTC, merged